# Lade mehrere Docker Compose Dateien
docker_compose([
    # 'manifests/gateway/docker-compose.yaml',
    # 'manifests/messaging/docker-compose.yaml',
    # 'manifests/monitor/docker-compose.yaml',
    # 'manifests/processing/docker-compose.yaml'
    'http-producer/docker-compose.yaml'
])


